// Team kit colours — keyed purely by team name (lowercased).
// Name-based lookup is used because it matches exactly what API-Football returns
// in fixture responses, eliminating ID uncertainty entirely.
//
// getTeamColours(teamId, teamName?) — ignores teamId, looks up by name.
// teamId kept in signature for backwards compatibility with callers.

type Colours = { primary: string; secondary: string };

const TEAM_COLOURS: Record<string, Colours> = {

  // ============================================================
  // PREMIER LEAGUE 2025-26
  // ============================================================
  'arsenal': { primary: '#EF0107', secondary: '#FFFFFF' },
  'aston villa': { primary: '#670E36', secondary: '#95BFE5' },
  'bournemouth': { primary: '#DA291C', secondary: '#000000' },
  'afc bournemouth': { primary: '#DA291C', secondary: '#000000' },
  'brentford': { primary: '#E30613', secondary: '#FFFFFF' },
  'brighton': { primary: '#0057B8', secondary: '#FFFFFF' },
  'brighton & hove albion': { primary: '#0057B8', secondary: '#FFFFFF' },
  'brighton and hove albion': { primary: '#0057B8', secondary: '#FFFFFF' },
  'chelsea': { primary: '#034694', secondary: '#FFFFFF' },
  'crystal palace': { primary: '#1B458F', secondary: '#C4122E' },
  'everton': { primary: '#003399', secondary: '#FFFFFF' },
  'fulham': { primary: '#FFFFFF', secondary: '#000000' },
  'ipswich': { primary: '#3A64A3', secondary: '#FFFFFF' },
  'ipswich town': { primary: '#3A64A3', secondary: '#FFFFFF' },
  'leicester': { primary: '#003090', secondary: '#FDBE11' },
  'leicester city': { primary: '#003090', secondary: '#FDBE11' },
  'liverpool': { primary: '#C8102E', secondary: '#FFFFFF' },
  'manchester city': { primary: '#6CABDD', secondary: '#FFFFFF' },
  'manchester united': { primary: '#DA291C', secondary: '#FFFFFF' },
  'newcastle': { primary: '#241F20', secondary: '#FFFFFF' },
  'newcastle united': { primary: '#241F20', secondary: '#FFFFFF' },
  'nottingham forest': { primary: '#DD0000', secondary: '#FFFFFF' },
  'southampton': { primary: '#D71920', secondary: '#FFFFFF' },
  'tottenham': { primary: '#132257', secondary: '#FFFFFF' },
  'tottenham hotspur': { primary: '#132257', secondary: '#FFFFFF' },
  'west ham': { primary: '#7A263A', secondary: '#59C2E6' },
  'west ham united': { primary: '#7A263A', secondary: '#59C2E6' },
  'wolverhampton wanderers': { primary: '#FDB913', secondary: '#231F20' },
  'wolves': { primary: '#FDB913', secondary: '#231F20' },

  // ============================================================
  // EFL CHAMPIONSHIP 2025-26
  // ============================================================
  'burnley': { primary: '#6C1D45', secondary: '#99D6EA' },
  'cardiff city': { primary: '#003DA5', secondary: '#FFFFFF' },
  'cardiff': { primary: '#003DA5', secondary: '#FFFFFF' },
  'coventry city': { primary: '#62B5E5', secondary: '#FFFFFF' },
  'coventry': { primary: '#62B5E5', secondary: '#FFFFFF' },
  'derby county': { primary: '#FFFFFF', secondary: '#000000' },
  'hull city': { primary: '#F5A623', secondary: '#000000' },
  'hull': { primary: '#F5A623', secondary: '#000000' },
  'leeds united': { primary: '#FFFFFF', secondary: '#1D428A' },
  'leeds': { primary: '#FFFFFF', secondary: '#1D428A' },
  'luton town': { primary: '#F78E1E', secondary: '#FFFFFF' },
  'luton': { primary: '#F78E1E', secondary: '#FFFFFF' },
  'middlesbrough': { primary: '#DC002E', secondary: '#FFFFFF' },
  'boro': { primary: '#DC002E', secondary: '#FFFFFF' },
  'millwall': { primary: '#001D5E', secondary: '#FFFFFF' },
  'norwich city': { primary: '#FFF200', secondary: '#00A650' },
  'norwich': { primary: '#FFF200', secondary: '#00A650' },
  'oxford united': { primary: '#F5D130', secondary: '#002D62' },
  'oxford': { primary: '#F5D130', secondary: '#002D62' },
  'plymouth argyle': { primary: '#003E2F', secondary: '#FFFFFF' },
  'plymouth': { primary: '#003E2F', secondary: '#FFFFFF' },
  'portsmouth': { primary: '#001489', secondary: '#FFFFFF' },
  'preston north end': { primary: '#FFFFFF', secondary: '#1E3A5F' },
  'preston': { primary: '#FFFFFF', secondary: '#1E3A5F' },
  'qpr': { primary: '#1D5BA4', secondary: '#FFFFFF' },
  'queens park rangers': { primary: '#1D5BA4', secondary: '#FFFFFF' },
  'sheffield united': { primary: '#EE2737', secondary: '#FFFFFF' },
  'sheffield utd': { primary: '#EE2737', secondary: '#FFFFFF' },
  'sheff utd': { primary: '#EE2737', secondary: '#FFFFFF' },
  'sheffield wednesday': { primary: '#0066B2', secondary: '#FFFFFF' },
  'sheff wed': { primary: '#0066B2', secondary: '#FFFFFF' },
  'stoke city': { primary: '#E03A3E', secondary: '#FFFFFF' },
  'stoke': { primary: '#E03A3E', secondary: '#FFFFFF' },
  'sunderland': { primary: '#EB172B', secondary: '#FFFFFF' },
  'swansea city': { primary: '#FFFFFF', secondary: '#000000' },
  'swansea': { primary: '#FFFFFF', secondary: '#000000' },
  'watford': { primary: '#FBEE23', secondary: '#000000' },
  'west bromwich albion': { primary: '#122F67', secondary: '#FFFFFF' },
  'west brom': { primary: '#122F67', secondary: '#FFFFFF' },

  // ============================================================
  // EFL LEAGUE ONE 2025-26
  // ============================================================
  'barnsley': { primary: '#CC0000', secondary: '#FFFFFF' },
  'birmingham city': { primary: '#0000FF', secondary: '#FFFFFF' },
  'birmingham': { primary: '#0000FF', secondary: '#FFFFFF' },
  'blackpool': { primary: '#F68712', secondary: '#FFFFFF' },
  'bolton wanderers': { primary: '#FFFFFF', secondary: '#003DA5' },
  'bolton': { primary: '#FFFFFF', secondary: '#003DA5' },
  'bristol rovers': { primary: '#003DA5', secondary: '#FFFFFF' },
  'burton albion': { primary: '#F5A623', secondary: '#000000' },
  'burton': { primary: '#F5A623', secondary: '#000000' },
  'cambridge united': { primary: '#F5A623', secondary: '#000000' },
  'cambridge': { primary: '#F5A623', secondary: '#000000' },
  'charlton athletic': { primary: '#CC0000', secondary: '#FFFFFF' },
  'charlton': { primary: '#CC0000', secondary: '#FFFFFF' },
  'exeter city': { primary: '#CC0000', secondary: '#FFFFFF' },
  'exeter': { primary: '#CC0000', secondary: '#FFFFFF' },
  'huddersfield town': { primary: '#0E63AD', secondary: '#FFFFFF' },
  'huddersfield': { primary: '#0E63AD', secondary: '#FFFFFF' },
  'leyton orient': { primary: '#CC0000', secondary: '#FFFFFF' },
  'lincoln city': { primary: '#CC0000', secondary: '#FFFFFF' },
  'lincoln': { primary: '#CC0000', secondary: '#FFFFFF' },
  'northampton town': { primary: '#A81B23', secondary: '#FFFFFF' },
  'northampton': { primary: '#A81B23', secondary: '#FFFFFF' },
  'peterborough united': { primary: '#0055A4', secondary: '#FFFFFF' },
  'peterborough': { primary: '#0055A4', secondary: '#FFFFFF' },
  'reading': { primary: '#004494', secondary: '#FFFFFF' },
  'rotherham united': { primary: '#CC0000', secondary: '#FFFFFF' },
  'rotherham': { primary: '#CC0000', secondary: '#FFFFFF' },
  'shrewsbury town': { primary: '#003DA5', secondary: '#FFCC00' },
  'shrewsbury': { primary: '#003DA5', secondary: '#FFCC00' },
  'stockport county': { primary: '#003DA5', secondary: '#FFFFFF' },
  'stockport': { primary: '#003DA5', secondary: '#FFFFFF' },
  'wigan athletic': { primary: '#003DA5', secondary: '#FFFFFF' },
  'wigan': { primary: '#003DA5', secondary: '#FFFFFF' },
  'wrexham': { primary: '#CC0000', secondary: '#FFFFFF' },
  'wycombe wanderers': { primary: '#003DA5', secondary: '#FFFFFF' },
  'wycombe': { primary: '#003DA5', secondary: '#FFFFFF' },
  'blackburn rovers': { primary: '#003DA5', secondary: '#FFFFFF' },
  'blackburn': { primary: '#003DA5', secondary: '#FFFFFF' },
  'bristol city': { primary: '#E21836', secondary: '#FFFFFF' },
  'stevenage': { primary: '#CC0000', secondary: '#FFFFFF' },

  // ============================================================
  // EFL LEAGUE TWO 2025-26 + other lower league clubs
  // ============================================================
  'bradford city': { primary: '#A30036', secondary: '#FFCD00' },
  'bradford': { primary: '#A30036', secondary: '#FFCD00' },
  'doncaster rovers': { primary: '#CC0000', secondary: '#FFFFFF' },
  'doncaster': { primary: '#CC0000', secondary: '#FFFFFF' },
  'mansfield town': { primary: '#F5A623', secondary: '#003DA5' },
  'mansfield': { primary: '#F5A623', secondary: '#003DA5' },
  'accrington stanley': { primary: '#CC0000', secondary: '#FFFFFF' },
  'accrington': { primary: '#CC0000', secondary: '#FFFFFF' },
  'afc wimbledon': { primary: '#003DA5', secondary: '#FFCD00' },
  'wimbledon': { primary: '#003DA5', secondary: '#FFCD00' },
  'barrow': { primary: '#003DA5', secondary: '#FFFFFF' },
  'carlisle united': { primary: '#003DA5', secondary: '#CC0000' },
  'carlisle': { primary: '#003DA5', secondary: '#CC0000' },
  'cheltenham town': { primary: '#CC0000', secondary: '#FFFFFF' },
  'cheltenham': { primary: '#CC0000', secondary: '#FFFFFF' },
  'colchester united': { primary: '#003DA5', secondary: '#FFCD00' },
  'colchester': { primary: '#003DA5', secondary: '#FFCD00' },
  'crawley town': { primary: '#CC0000', secondary: '#FFFFFF' },
  'crawley': { primary: '#CC0000', secondary: '#FFFFFF' },
  'crewe alexandra': { primary: '#CC0000', secondary: '#FFFFFF' },
  'crewe': { primary: '#CC0000', secondary: '#FFFFFF' },
  'fleetwood town': { primary: '#CC0000', secondary: '#FFFFFF' },
  'fleetwood': { primary: '#CC0000', secondary: '#FFFFFF' },
  'forest green rovers': { primary: '#00A650', secondary: '#FFFFFF' },
  'forest green': { primary: '#00A650', secondary: '#FFFFFF' },
  'gillingham': { primary: '#003DA5', secondary: '#FFFFFF' },
  'grimsby town': { primary: '#000000', secondary: '#FFFFFF' },
  'grimsby': { primary: '#000000', secondary: '#FFFFFF' },
  'harrogate town': { primary: '#FFCD00', secondary: '#000000' },
  'harrogate': { primary: '#FFCD00', secondary: '#000000' },
  'mfc': { primary: '#DC002E', secondary: '#FFFFFF' },
  'mkdons': { primary: '#003DA5', secondary: '#FFCD00' },
  'mk dons': { primary: '#003DA5', secondary: '#FFCD00' },
  'milton keynes dons': { primary: '#003DA5', secondary: '#FFCD00' },
  'morecambe': { primary: '#CC0000', secondary: '#FFFFFF' },
  'newport county': { primary: '#F5A623', secondary: '#000000' },
  'newport': { primary: '#F5A623', secondary: '#000000' },
  'notts county': { primary: '#000000', secondary: '#FFFFFF' },
  'oldham athletic': { primary: '#003DA5', secondary: '#CC0000' },
  'oldham': { primary: '#003DA5', secondary: '#CC0000' },
  'port vale': { primary: '#003DA5', secondary: '#FFCD00' },
  'rochdale': { primary: '#003DA5', secondary: '#FFFFFF' },
  'salford city': { primary: '#CC0000', secondary: '#000000' },
  'salford': { primary: '#CC0000', secondary: '#000000' },
  'swindon town': { primary: '#CC0000', secondary: '#FFFFFF' },
  'swindon': { primary: '#CC0000', secondary: '#FFFFFF' },
  'tranmere rovers': { primary: '#FFFFFF', secondary: '#003DA5' },
  'tranmere': { primary: '#FFFFFF', secondary: '#003DA5' },
  'walsall': { primary: '#CC0000', secondary: '#FFFFFF' },
  'yeovil town': { primary: '#006400', secondary: '#FFFFFF' },
  'yeovil': { primary: '#006400', secondary: '#FFFFFF' },
  'chesterfield': { primary: '#003DA5', secondary: '#FFFFFF' },
  'dag & red': { primary: '#CC0000', secondary: '#FFFFFF' },
  'dagenham & redbridge': { primary: '#CC0000', secondary: '#FFFFFF' },
  'sutton united': { primary: '#F5A623', secondary: '#000000' },
  'sutton': { primary: '#F5A623', secondary: '#000000' },
  'hartlepool united': { primary: '#003DA5', secondary: '#FFFFFF' },
  'hartlepool': { primary: '#003DA5', secondary: '#FFFFFF' },
  'ipswich town w': { primary: '#3A64A3', secondary: '#FFFFFF' },
  'charlton athletic w': { primary: '#CC0000', secondary: '#FFFFFF' },
  'liverpool w': { primary: '#C8102E', secondary: '#FFFFFF' },
  'manchester city w': { primary: '#6CABDD', secondary: '#FFFFFF' },
  'tottenham hotspur w': { primary: '#132257', secondary: '#FFFFFF' },
  'aston villa w': { primary: '#670E36', secondary: '#95BFE5' },
  'brighton & hove albion w': { primary: '#0057B8', secondary: '#FFFFFF' },
  'west ham united w': { primary: '#7A263A', secondary: '#59C2E6' },

  // ============================================================
  // LA LIGA 2025-26
  // ============================================================
  'real madrid': { primary: '#FFFFFF', secondary: '#FEBE10' },
  'barcelona': { primary: '#A50044', secondary: '#004D98' },
  'fc barcelona': { primary: '#A50044', secondary: '#004D98' },
  'atletico madrid': { primary: '#CB3524', secondary: '#FFFFFF' },
  'atlético madrid': { primary: '#CB3524', secondary: '#FFFFFF' },
  'athletic bilbao': { primary: '#EE2523', secondary: '#FFFFFF' },
  'athletic club': { primary: '#EE2523', secondary: '#FFFFFF' },
  'valencia': { primary: '#FFFFFF', secondary: '#000000' },
  'valencia cf': { primary: '#FFFFFF', secondary: '#000000' },
  'villarreal': { primary: '#FFCD00', secondary: '#005BAA' },
  'villarreal cf': { primary: '#FFCD00', secondary: '#005BAA' },
  'real sociedad': { primary: '#003DA5', secondary: '#FFFFFF' },
  'real betis': { primary: '#00954C', secondary: '#FFFFFF' },
  'sevilla': { primary: '#FFFFFF', secondary: '#D20515' },
  'sevilla fc': { primary: '#FFFFFF', secondary: '#D20515' },
  'celta vigo': { primary: '#8AC3EE', secondary: '#FFFFFF' },
  'rc celta': { primary: '#8AC3EE', secondary: '#FFFFFF' },
  'osasuna': { primary: '#D91A2A', secondary: '#0A1E5C' },
  'ca osasuna': { primary: '#D91A2A', secondary: '#0A1E5C' },
  'girona': { primary: '#CC2635', secondary: '#FFFFFF' },
  'girona fc': { primary: '#CC2635', secondary: '#FFFFFF' },
  'getafe': { primary: '#005999', secondary: '#FFFFFF' },
  'getafe cf': { primary: '#005999', secondary: '#FFFFFF' },
  'rayo vallecano': { primary: '#CC0000', secondary: '#FFFFFF' },
  'espanyol': { primary: '#007FC8', secondary: '#FFFFFF' },
  'rcd espanyol': { primary: '#007FC8', secondary: '#FFFFFF' },
  'real valladolid': { primary: '#6B3FA0', secondary: '#FFFFFF' },
  'valladolid': { primary: '#6B3FA0', secondary: '#FFFFFF' },
  'deportivo alaves': { primary: '#003DA5', secondary: '#FFFFFF' },
  'alaves': { primary: '#003DA5', secondary: '#FFFFFF' },
  'deportivo alavés': { primary: '#003DA5', secondary: '#FFFFFF' },
  'mallorca': { primary: '#E03C31', secondary: '#000000' },
  'rcd mallorca': { primary: '#E03C31', secondary: '#000000' },
  'las palmas': { primary: '#FFDD00', secondary: '#003DA5' },
  'ud las palmas': { primary: '#FFDD00', secondary: '#003DA5' },
  'leganes': { primary: '#003DA5', secondary: '#FFFFFF' },
  'cd leganes': { primary: '#003DA5', secondary: '#FFFFFF' },

  // ============================================================
  // BUNDESLIGA 2025-26
  // ============================================================
  'bayern munich': { primary: '#DC052D', secondary: '#FFFFFF' },
  'fc bayern münchen': { primary: '#DC052D', secondary: '#FFFFFF' },
  'fc bayern munich': { primary: '#DC052D', secondary: '#FFFFFF' },
  'borussia dortmund': { primary: '#FDE100', secondary: '#000000' },
  'bayer leverkusen': { primary: '#E32221', secondary: '#000000' },
  'rb leipzig': { primary: '#DD0741', secondary: '#FFFFFF' },
  'eintracht frankfurt': { primary: '#000000', secondary: '#E1000F' },
  'vfb stuttgart': { primary: '#FFFFFF', secondary: '#E32219' },
  'stuttgart': { primary: '#FFFFFF', secondary: '#E32219' },
  'sc freiburg': { primary: '#E30613', secondary: '#FFFFFF' },
  'freiburg': { primary: '#E30613', secondary: '#FFFFFF' },
  'tsg hoffenheim': { primary: '#1C63B7', secondary: '#FFFFFF' },
  'hoffenheim': { primary: '#1C63B7', secondary: '#FFFFFF' },
  'vfl wolfsburg': { primary: '#65B32E', secondary: '#FFFFFF' },
  'wolfsburg': { primary: '#65B32E', secondary: '#FFFFFF' },
  'werder bremen': { primary: '#1D9053', secondary: '#FFFFFF' },
  'sv werder bremen': { primary: '#1D9053', secondary: '#FFFFFF' },
  'borussia monchengladbach': { primary: '#000000', secondary: '#1FA149' },
  'borussia mönchengladbach': { primary: '#000000', secondary: '#1FA149' },
  'fc union berlin': { primary: '#EB1923', secondary: '#FFFFFF' },
  'union berlin': { primary: '#EB1923', secondary: '#FFFFFF' },
  '1. fc union berlin': { primary: '#EB1923', secondary: '#FFFFFF' },
  'fc augsburg': { primary: '#BA3733', secondary: '#FFFFFF' },
  'augsburg': { primary: '#BA3733', secondary: '#FFFFFF' },
  'vfl bochum': { primary: '#005BA1', secondary: '#FFFFFF' },
  'bochum': { primary: '#005BA1', secondary: '#FFFFFF' },
  '1. fc heidenheim': { primary: '#D40511', secondary: '#003DA5' },
  'heidenheim': { primary: '#D40511', secondary: '#003DA5' },
  'fc st. pauli': { primary: '#6E3B23', secondary: '#FFFFFF' },
  'st. pauli': { primary: '#6E3B23', secondary: '#FFFFFF' },
  'holstein kiel': { primary: '#003DA5', secondary: '#FFFFFF' },
  'kiel': { primary: '#003DA5', secondary: '#FFFFFF' },
  '1. fc koln': { primary: '#FFFFFF', secondary: '#CC0000' },
  '1. fc köln': { primary: '#FFFFFF', secondary: '#CC0000' },
  'fc koln': { primary: '#FFFFFF', secondary: '#CC0000' },
  'hertha bsc': { primary: '#005DAC', secondary: '#FFFFFF' },
  'hertha': { primary: '#005DAC', secondary: '#FFFFFF' },
  'sv darmstadt 98': { primary: '#004E9E', secondary: '#FFFFFF' },
  'darmstadt': { primary: '#004E9E', secondary: '#FFFFFF' },

  // ============================================================
  // PRIMEIRA LIGA 2025-26
  // ============================================================
  'benfica': { primary: '#E20714', secondary: '#FFFFFF' },
  'sl benfica': { primary: '#E20714', secondary: '#FFFFFF' },
  'sporting cp': { primary: '#006847', secondary: '#FFFFFF' },
  'sporting lisbon': { primary: '#006847', secondary: '#FFFFFF' },
  'sporting clube de portugal': { primary: '#006847', secondary: '#FFFFFF' },
  'fc porto': { primary: '#003DA5', secondary: '#FFFFFF' },
  'porto': { primary: '#003DA5', secondary: '#FFFFFF' },
  'sc braga': { primary: '#CC0000', secondary: '#FFFFFF' },
  'braga': { primary: '#CC0000', secondary: '#FFFFFF' },
  'vitoria sc': { primary: '#006400', secondary: '#FFFFFF' },
  'vitoria de guimaraes': { primary: '#006400', secondary: '#FFFFFF' },
  'casa pia': { primary: '#003DA5', secondary: '#FFFFFF' },
  'famalicao': { primary: '#006847', secondary: '#FFFFFF' },
  'fc famalicao': { primary: '#006847', secondary: '#FFFFFF' },
  'boavista': { primary: '#000000', secondary: '#FFFFFF' },
  'boavista fc': { primary: '#000000', secondary: '#FFFFFF' },
  'estoril': { primary: '#FFCD00', secondary: '#000000' },
  'estoril praia': { primary: '#FFCD00', secondary: '#000000' },
  'moreirense': { primary: '#006400', secondary: '#FFFFFF' },
  'rio ave': { primary: '#006400', secondary: '#FFFFFF' },
  'santa clara': { primary: '#CC0000', secondary: '#FFFFFF' },
  'cd santa clara': { primary: '#CC0000', secondary: '#FFFFFF' },
  'nacional': { primary: '#000000', secondary: '#FFFFFF' },
  'cd nacional': { primary: '#000000', secondary: '#FFFFFF' },
  'estrela amadora': { primary: '#CC0000', secondary: '#000000' },
  'gil vicente': { primary: '#000000', secondary: '#CC0000' },

  // ============================================================
  // CHAMPIONS LEAGUE — additional clubs not above
  // ============================================================
  'paris saint-germain': { primary: '#004170', secondary: '#DA291C' },
  'paris saint germain': { primary: '#004170', secondary: '#DA291C' },
  'psg': { primary: '#004170', secondary: '#DA291C' },
  'juventus': { primary: '#000000', secondary: '#FFFFFF' },
  'ac milan': { primary: '#FB090B', secondary: '#000000' },
  'inter milan': { primary: '#009DDC', secondary: '#000000' },
  'inter': { primary: '#009DDC', secondary: '#000000' },
  'fc internazionale': { primary: '#009DDC', secondary: '#000000' },
  'internazionale': { primary: '#009DDC', secondary: '#000000' },
  'napoli': { primary: '#12A0D7', secondary: '#FFFFFF' },
  'ssc napoli': { primary: '#12A0D7', secondary: '#FFFFFF' },
  'as roma': { primary: '#8E1F2F', secondary: '#F5A623' },
  'roma': { primary: '#8E1F2F', secondary: '#F5A623' },
  'atalanta': { primary: '#1E71B8', secondary: '#000000' },
  'atalanta bc': { primary: '#1E71B8', secondary: '#000000' },
  'lazio': { primary: '#87CEEB', secondary: '#FFFFFF' },
  'ss lazio': { primary: '#87CEEB', secondary: '#FFFFFF' },
  'fiorentina': { primary: '#482E92', secondary: '#FFFFFF' },
  'acf fiorentina': { primary: '#482E92', secondary: '#FFFFFF' },
  'bologna': { primary: '#1A2C5B', secondary: '#A71C2F' },
  'fc bologna': { primary: '#1A2C5B', secondary: '#A71C2F' },
  'torino': { primary: '#8B1C2F', secondary: '#FFFFFF' },
  'as monaco': { primary: '#E30613', secondary: '#FFFFFF' },
  'monaco': { primary: '#E30613', secondary: '#FFFFFF' },
  'olympique lyonnais': { primary: '#FFFFFF', secondary: '#D2122E' },
  'lyon': { primary: '#FFFFFF', secondary: '#D2122E' },
  'olympique de marseille': { primary: '#2FAEE0', secondary: '#FFFFFF' },
  'marseille': { primary: '#2FAEE0', secondary: '#FFFFFF' },
  'lille': { primary: '#DA291C', secondary: '#FFFFFF' },
  'losc lille': { primary: '#DA291C', secondary: '#FFFFFF' },
  'rc lens': { primary: '#CC0000', secondary: '#FFD700' },
  'lens': { primary: '#CC0000', secondary: '#FFD700' },
  'stade rennais': { primary: '#DA291C', secondary: '#000000' },
  'rennes': { primary: '#DA291C', secondary: '#000000' },
  'nice': { primary: '#CC0000', secondary: '#000000' },
  'ogc nice': { primary: '#CC0000', secondary: '#000000' },
  'psv eindhoven': { primary: '#CC0000', secondary: '#FFFFFF' },
  'psv': { primary: '#CC0000', secondary: '#FFFFFF' },
  'ajax': { primary: '#CC0000', secondary: '#FFFFFF' },
  'afc ajax': { primary: '#CC0000', secondary: '#FFFFFF' },
  'feyenoord': { primary: '#CC0000', secondary: '#FFFFFF' },
  'celtic': { primary: '#00843D', secondary: '#FFFFFF' },
  'rangers': { primary: '#0000FF', secondary: '#FFFFFF' },
  'shakhtar donetsk': { primary: '#FF6600', secondary: '#000000' },
  'shakhtar': { primary: '#FF6600', secondary: '#000000' },
  'red bull salzburg': { primary: '#CC0000', secondary: '#FFFFFF' },
  'rb salzburg': { primary: '#CC0000', secondary: '#FFFFFF' },
  'club brugge': { primary: '#003DA5', secondary: '#000000' },
  'anderlecht': { primary: '#6B4EAE', secondary: '#FFFFFF' },
  'galatasaray': { primary: '#CC0000', secondary: '#FFCD00' },
  'fenerbahce': { primary: '#003DA5', secondary: '#FFCD00' },
  'besiktas': { primary: '#000000', secondary: '#FFFFFF' },

  // ============================================================
  // INTERNATIONAL: Home Nations + Ireland
  // ============================================================
  'england': { primary: '#FFFFFF', secondary: '#002395' },
  'scotland': { primary: '#003087', secondary: '#FFFFFF' },
  'wales': { primary: '#D20515', secondary: '#FFFFFF' },
  'northern ireland': { primary: '#006847', secondary: '#FFFFFF' },
  'republic of ireland': { primary: '#009A49', secondary: '#FFFFFF' },
  'ireland': { primary: '#009A49', secondary: '#FFFFFF' },

  // ============================================================
  // INTERNATIONAL: Europe
  // ============================================================
  'france': { primary: '#002395', secondary: '#FFFFFF' },
  'germany': { primary: '#FFFFFF', secondary: '#000000' },
  'spain': { primary: '#DA291C', secondary: '#FFCD00' },
  'italy': { primary: '#0066CC', secondary: '#FFFFFF' },
  'portugal': { primary: '#DA291C', secondary: '#006847' },
  'netherlands': { primary: '#FF6600', secondary: '#FFFFFF' },
  'holland': { primary: '#FF6600', secondary: '#FFFFFF' },
  'belgium': { primary: '#CC0000', secondary: '#FFCD00' },
  'croatia': { primary: '#FF0000', secondary: '#FFFFFF' },
  'denmark': { primary: '#DA291C', secondary: '#FFFFFF' },
  'turkey': { primary: '#CE1124', secondary: '#FFFFFF' },
  'sweden': { primary: '#FFCD00', secondary: '#003DA5' },
  'poland': { primary: '#FFFFFF', secondary: '#DC143C' },
  'austria': { primary: '#DC143C', secondary: '#FFFFFF' },
  'switzerland': { primary: '#DA291C', secondary: '#FFFFFF' },
  'serbia': { primary: '#DA291C', secondary: '#003DA5' },
  'ukraine': { primary: '#FFCD00', secondary: '#003DA5' },
  'romania': { primary: '#FFCD00', secondary: '#003DA5' },
  'greece': { primary: '#005DAC', secondary: '#FFFFFF' },
  'norway': { primary: '#DA291C', secondary: '#FFFFFF' },
  'czech republic': { primary: '#003087', secondary: '#FFFFFF' },
  'czechia': { primary: '#003087', secondary: '#FFFFFF' },
  'hungary': { primary: '#CE2939', secondary: '#477050' },
  'finland': { primary: '#FFFFFF', secondary: '#003580' },
  'iceland': { primary: '#003897', secondary: '#D72828' },
  'slovenia': { primary: '#005DA5', secondary: '#FFFFFF' },
  'slovakia': { primary: '#003DA5', secondary: '#FFFFFF' },
  'albania': { primary: '#DA291C', secondary: '#000000' },
  'georgia': { primary: '#FFFFFF', secondary: '#DA291C' },
  'bosnia and herzegovina': { primary: '#003DA5', secondary: '#FFCD00' },
  'bosnia & herzegovina': { primary: '#003DA5', secondary: '#FFCD00' },
  'montenegro': { primary: '#CC0000', secondary: '#FFD700' },
  'north macedonia': { primary: '#CC0000', secondary: '#FFCD00' },
  'bulgaria': { primary: '#FFFFFF', secondary: '#00966E' },
  'russia': { primary: '#FFFFFF', secondary: '#DA291C' },
  'kosovo': { primary: '#003DA5', secondary: '#FFD700' },
  'luxembourg': { primary: '#DA291C', secondary: '#009FDA' },
  'israel': { primary: '#FFFFFF', secondary: '#003DA5' },

  // ============================================================
  // INTERNATIONAL: South America
  // ============================================================
  'brazil': { primary: '#FFCC00', secondary: '#009B3A' },
  'argentina': { primary: '#75AADB', secondary: '#FFFFFF' },
  'colombia': { primary: '#FFCC00', secondary: '#003DA5' },
  'uruguay': { primary: '#75AADB', secondary: '#FFFFFF' },
  'chile': { primary: '#CC0000', secondary: '#FFFFFF' },
  'paraguay': { primary: '#CC0000', secondary: '#003DA5' },
  'peru': { primary: '#FFFFFF', secondary: '#CC0000' },
  'ecuador': { primary: '#FFCD00', secondary: '#003DA5' },
  'venezuela': { primary: '#8D1B3D', secondary: '#FFFFFF' },
  'bolivia': { primary: '#007A33', secondary: '#FFCD00' },

  // ============================================================
  // INTERNATIONAL: Asia
  // ============================================================
  'japan': { primary: '#003087', secondary: '#FFFFFF' },
  'south korea': { primary: '#CC0000', secondary: '#003DA5' },
  'korea republic': { primary: '#CC0000', secondary: '#003DA5' },
  'iran': { primary: '#FFFFFF', secondary: '#CC0000' },
  'saudi arabia': { primary: '#009639', secondary: '#FFFFFF' },
  'qatar': { primary: '#8D1B3D', secondary: '#FFFFFF' },
  'australia': { primary: '#FFB81C', secondary: '#00843D' },
  'uzbekistan': { primary: '#FFFFFF', secondary: '#009FDA' },
  'iraq': { primary: '#FFFFFF', secondary: '#007A33' },
  'china': { primary: '#CC0000', secondary: '#FFCD00' },
  'china pr': { primary: '#CC0000', secondary: '#FFCD00' },
  'united arab emirates': { primary: '#FFFFFF', secondary: '#CC0000' },

  // ============================================================
  // INTERNATIONAL: Africa
  // ============================================================
  'morocco': { primary: '#CC0000', secondary: '#009900' },
  'cameroon': { primary: '#007A33', secondary: '#CC0000' },
  'south africa': { primary: '#007749', secondary: '#FFB81C' },
  'egypt': { primary: '#CC0000', secondary: '#FFFFFF' },
  'nigeria': { primary: '#006600', secondary: '#FFFFFF' },
  'senegal': { primary: '#006600', secondary: '#FFCD00' },
  'ghana': { primary: '#FFFFFF', secondary: '#006B3F' },
  'tunisia': { primary: '#CC0000', secondary: '#FFFFFF' },
  'algeria': { primary: '#006633', secondary: '#FFFFFF' },
  'ivory coast': { primary: '#FF6600', secondary: '#009E49' },
  "cote d'ivoire": { primary: '#FF6600', secondary: '#009E49' },
  'mali': { primary: '#006600', secondary: '#FFCD00' },
  'dr congo': { primary: '#007FFF', secondary: '#CC0000' },
  'congo dr': { primary: '#007FFF', secondary: '#CC0000' },

  // ============================================================
  // INTERNATIONAL: CONCACAF
  // ============================================================
  'mexico': { primary: '#006847', secondary: '#FFFFFF' },
  'usa': { primary: '#FFFFFF', secondary: '#003DA5' },
  'united states': { primary: '#FFFFFF', secondary: '#003DA5' },
  'canada': { primary: '#CC0000', secondary: '#FFFFFF' },
  'costa rica': { primary: '#CC0000', secondary: '#003DA5' },
  'jamaica': { primary: '#FFB81C', secondary: '#009B3A' },
  'panama': { primary: '#CC0000', secondary: '#003DA5' },
  'honduras': { primary: '#003DA5', secondary: '#FFFFFF' },
  'new zealand': { primary: '#FFFFFF', secondary: '#000000' },

  // Women's Champions League
  'barcelona w': { primary: '#A50044', secondary: '#004D98' },
  'real madrid w': { primary: '#FFFFFF', secondary: '#FEBE10' },
  'lyon w': { primary: '#FFFFFF', secondary: '#D2122E' },
  'vfl wolfsburg w': { primary: '#65B32E', secondary: '#FFFFFF' },
  'chelsea w': { primary: '#034694', secondary: '#FFFFFF' },
  'arsenal w': { primary: '#EF0107', secondary: '#FFFFFF' },
  'bayern munich w': { primary: '#DC052D', secondary: '#FFFFFF' },
  'manchester united w': { primary: '#DA291C', secondary: '#FBE122' },
};

const DEFAULT_COLOURS: Colours = { primary: '#334155', secondary: '#94a3b8' };

export function getTeamColours(_teamId: number, teamName?: string): Colours {
  if (teamName) {
    const match = TEAM_COLOURS[teamName.toLowerCase()];
    if (match) return match;
  }
  return DEFAULT_COLOURS;
}

export function getTeamGradient(homeTeamId: number, awayTeamId: number, homeTeamName?: string, awayTeamName?: string): string {
  const home = getTeamColours(homeTeamId, homeTeamName);
  const away = getTeamColours(awayTeamId, awayTeamName);
  return `linear-gradient(135deg, ${home.primary}40 0%, transparent 50%, ${away.primary}40 100%)`;
}
